import { Container } from "inversify";
import { CardapioController } from "../CardapioController";
import { IController } from "../IController";
import { MainController } from "../MainController";
import { ReservaController } from "../ReservaController";
import ControllerTypes from "./ControllerTypes";
const ControllerContainer = new Container();
ControllerContainer.bind<IController>(ControllerTypes.Controller).to(MainController);
ControllerContainer.bind<IController>(ControllerTypes.Controller).to(CardapioController);
ControllerContainer.bind<IController>(ControllerTypes.Controller).to(ReservaController);
export default ControllerContainer;